### ISSUE TITLE
Create a pull request Template

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/edu-server#1]
Create a pull request that covers all the requirements for A perfect Pull request and is not limited to:
- Perfect code style check
- successful build
- No console errors
- No console warnings (sometimes)
- Pull request against branch name
- responsive UI
- Test case being passed

**Comment by atharmohammad** [comment]
@KeenWarrior  I would like to work on this issue

**Comment by KeenWarrior** [comment]
Sure @atharmohammad 

Go ahead

**Comment by tripathi-abhishek** [comment]
if possible please assign this to me if OP can't solve it.

**Comment by Akshit42-hue** [comment]
Do let me know if you want help @atharmohammad 
Really excited to contribute on this project

**Comment by atharmohammad** [comment]
> Do let me know if you want help @atharmohammad 
Sure 👍  @Akshit42-hue
