### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-server#11]
Hi @KeenWarrior,
After "npm install", when i run "npm run start", It is showing this: 

![image](https://user-images.githubusercontent.com/55191777/110784945-4fc2cc80-8290-11eb-9925-f54735e3fadc.png)

But ./service.json doesn't exist in the whole project.

**Comment by vasudev19126** [comment]
I am also facing the same issue

**Comment by ritvij14** [comment]
@rajatgupta24 @vasudev19126 

- To use the Firebase Admin SDK in the project, create a new firebase project using [firebase console](https://console.firebase.google.com/).
- After creating a project, go to [project settings](https://console.firebase.google.com/project/_/settings/general/).
- In project settings of your newly created project there will be tab called as "Service Accounts". 
- Click on it, then it will ask to create a service account, click to create a new service account.
- After creating a service account, click on generate new private key it will automatically download a json file.
- Copy the json file from your downloads folder and paste it into the project src/config folder and rename it to "service.json"

**Comment by rajatgupta24** [comment]
@ritvij14 Can i add that to contribute.md.

**Comment by ritvij14** [comment]
> @ritvij14 Can i add that to contribute.md.

@rajatgupta24 it is already being done by 2 people. You can check in the pull requests.

**Comment by ritvij14** [comment]
If this is solved then I think you can close the issue @rajatgupta24
