### ISSUE TITLE
Update README.md according to the Project Description

### ISSUE THREAD

**Issue by manishprivet** [codeforcauseorg/edu-server#16]
**Is your feature request related to a problem? Please describe.**
Right now more than half of the README is the same as that of a NestJS boilerplate, starting with the logo on the top.

**Describe the solution you'd like**

The README needs to be changed according to the project description.

**Comment by NeelParihar** [comment]
can i work on this ? @manishprivet

**Comment by ArchishmanSengupta** [comment]
can i work on this @Abhishek-kumar09 ?

**Comment by Abhishek-kumar09** [comment]
Please go on @NeelParihar.
@ArchishmanSengupta I will be tagging you to some newer issues, really sorry but @NeelParihar had early comment on issue, and I can't help you with that.

**Comment by ArchishmanSengupta** [comment]
No issues bhaiya

**Comment by Itsaadarsh** [comment]
Hey @Abhishek-kumar09, I'd love to contribute to this repository so tag me if a new issues comes up. 

Thanks!
