### ISSUE TITLE
Proper README Documentation starting from forking 

### ISSUE THREAD

**Issue by ArchishmanSengupta** [codeforcauseorg/edu-server#17]
I will modify the README FILE same like [this](https://github.com/codeforcauseorg/edu-client) starting from forking and how to contribute.

Please Assign me the task @KeenWarrior @kunal-kushwaha @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
@ArchishmanSengupta Please don't create duplicate issues, it is already hard to manage.
The issue is duplicate of https://github.com/codeforcauseorg/edu-server/issues/16
Ask if you want to work on previously created issue of same kind.

**Comment by ArchishmanSengupta** [comment]
oh i didn't see the issue. my bad. Can i work on #16 ?

**Comment by Abhishek-kumar09** [comment]
Please go on.
