### ISSUE TITLE
Edit README.md to provide steps of adding firebase admin credentials config file

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/edu-server#2]
Firebase admin credentials should not be stored in git. For that, every contributor needs to use their own firebase project account for development purposes.

Provide steps in README to make it easier for contributors.

**Comment by ritvij14** [comment]
@KeenWarrior I would like to take this up. Could you guide me a little as to how to get started with this?

**Comment by NeelParihar** [comment]
@KeenWarrior i have previously worked with firebase, i would love to work on it can you assign it to me?

**Comment by atharmohammad** [comment]
@ritvij14  Hey, you should first make a firebase account and setup the project on your account,then cupdate the readme.md file with the steps you followed,here (http://mariechatfield.com/tutorials/firebase/step1.html) you can see how to create a firebase project

**Comment by ritvij14** [comment]
> @ritvij14 Hey, you should first make a firebase account and setup the project on your account,then update the readme.md file with the steps you followed,here (http://mariechatfield.com/tutorials/firebase/step1.html) you can see how to create a firebase project

@atharmohammad thanks for explaining. I know Firebase basics and have already setup a project on my account. I tested out `firebase deploy` and it said that a Blaze payment plan is necessary for this. Am I doing something wrong or is this the correct way?

**Comment by ishandeveloper** [comment]
Hey @ritvij14 are you trying to deploy a firebase cloud function? If so, then you'll need to setup billing on your project, as firebase cloud functions have become paid as of Jan 1, 2021 onwards.

Although, I'd like to point out, I think working with firebase cloud functions is not necessary for this GitHub issue, as it's more writing steps about setting up a firebase project, generating admin sdk credentials and using free-tier firebase services such as cloud firestore, authentication etc.

Still, if you'd like to explore cloud functions on your own, feel free to hit up : )

**Comment by ritvij14** [comment]
@ishandeveloper thanks for the explanation. I went through the docs again and was able to do what this issue asked for :D.

**Comment by Amoghtech** [comment]
I want to work on this

**Comment by Amoghtech** [comment]
@KeenWarrior  I would like to work on this

**Comment by VenomFate-619** [comment]
I would like to take this up.

**Comment by Abhishek-kumar09** [comment]
Fixed with #5
