### ISSUE TITLE
Add docker compose under docker dir for MongoDB server spinup

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/edu-server#3]
The server is going to use MongoDB for execution. It will be easier to not setup DB locally and to use a docker container for the same.

## Required outcomes
 - Adding ```docker-compose.yml``` under ```docker``` dir
 - Add steps in README to spin up the container

**Comment by ritvij14** [comment]
@KeenWarrior I have done projects with docker and with the help of them already created a docker directory with docker-compose.yml as well. Could you please assign this issue to me?

**Comment by NeelParihar** [comment]
Do we need to add dockerfile in root of the project or in docker dir
