### ISSUE TITLE
Course Module for backend

### ISSUE THREAD

**Issue by ritvij14** [codeforcauseorg/edu-server#30]
**Is your feature request related to a problem? Please describe.**

We need to add schemas for the server for example users, courses, doubts, contests, assignments, etc. So that they can be properly stored in the database.

**Describe the solution you'd like**

Adding models of MongoDB schemas as described in docs for nestjs.

**Comment by ritvij14** [comment]
@KeenWarrior @Abhishek-kumar09 I would like to work on this, and hear suggestions from you, what more schemas would be needed for this project.

**Comment by Abhishek-kumar09** [comment]
Course Schema
Id
Name
Price
Start_date
End_date
Duration
Active
Coupons
No. of students
No. of videos
