### ISSUE TITLE
Schemas for backend 

### ISSUE THREAD

**Issue by Devesh21700Kumar** [codeforcauseorg/edu-server#34]
https://whimsical.com/XMU4Fx3UejnYUnvCetkXuc

I've made a place for all the common schemas in whimsical>

@Abhishek-kumar09 @KeenWarrior  it would be great if u could tell us about the schemas and also their objects ..
Then I can start making them and also send a PR for them

**Comment by Abhishek-kumar09** [comment]
This is the database model, you can edit and propose additions
https://dbdiagram.io/d/60647b79ecb54e10c33e25d8

**Comment by Devesh21700Kumar** [comment]
Thanks
