### ISSUE TITLE
Add contributors section in Readme 

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-server#42]
**Is your feature request related to a problem? Please describe.**

Add the contributor's section in the Readme.md like this :

![contributors](https://user-images.githubusercontent.com/64387054/112879288-944ec480-90e6-11eb-97e5-ee444ec88df3.PNG)

**Describe the solution you'd like**
 
Add required links 
for ex:  `<a href="https://github.com/codeforcauseorg/edu-server/graphs/contributors"> </a>`  for changing  image positions according to commits.

And for image you can use this `  <img src="https://contrib.rocks/image?repo=codeforcauseorg/edu-server" />`

And use proper formatting.

**Comment by Aayush-hub** [comment]
@Abhishek-kumar09 @Abhijay007 Can I work on this?
