### ISSUE TITLE
Setup swagger ui for api documentation

### ISSUE THREAD

**Issue by NeelParihar** [codeforcauseorg/edu-server#9]
setup swaggerui/openapi for api documentation, so that frontend developers will be able to know each an every api contract easily

references: https://docs.nestjs.com/openapi/introduction

**Comment by Abhishek-kumar09** [comment]
It will be a good leap to start with open API and swagger.

**Comment by Abhishek-kumar09** [comment]
Do you want to work on it?

**Comment by NeelParihar** [comment]
yes i can work on it

**Comment by Abhishek-kumar09** [comment]
Great then, do you also want to work on readme, or I assign it to someone else if you are more busy.

**Comment by NeelParihar** [comment]
yes i can work on both of them
