### ISSUE TITLE
Add wishlist courses to the user is misbehaving

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-server#91]
# Current Behaviour: 
Add Wishlist Course response
```
[
    {
        "cId": "6079e2c7294dcf960d3036be"
    }
]
cid should not be there, it should be stored in the form of array of courseId
```
# Expected Behaviour 
```
[
  { 
    ...all the course detail of the wishlist
  }
]
```

**Comment by dhwaj1902** [comment]
@Abhishek-kumar09 can you please explain with a little more explanation because I am not able to get it.

**Comment by Devesh21700Kumar** [comment]
> @Abhishek-kumar09 can you please explain with a little more explanation because I am not able to get it.

This issue was fixed actually.
@Abhishek-kumar09 will close it

**Comment by Abhishek-kumar09** [comment]
@dhwaj1902 Actually there was problem with the deleting the wishlist due to wrong way of inserting data. Now it is fixed :smile:
