### ISSUE TITLE
Delete Wishlist not working

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-server#92]
https://github.com/codeforcauseorg/edu-server/blob/d85b27f22f66becf5cc93f2628e61f6960640ad6/src/modules/user/user.controller.ts#L135-L155

The code is not working as expected due to way the way data is stored. It doesnt delete the wishlist course

**Comment by Abhishek-kumar09** [comment]
@Devesh21700Kumar

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09  issue has been resolved and changes have been committed to the latest PR

The fix:-
1). added a createWishlist dto with one object
2). destrcutrued cId as an object and then pushed into the array to get an array and not an array of objects.
3). filter method for delete was fixed according to the previous changes

#90  resolves this along with the addition of HTTP exception internal Server Error with appropriate message for all otehrs
