### ISSUE TITLE
Add Same Course in Wishlist array

### ISSUE THREAD

**Issue by dhwaj1902** [codeforcauseorg/edu-server#96]
**Describe the bug**
Right now we are able to add the same course multiple times in the wishlist array of the same user.

**To Reproduce**
We can resolve this by adding a condition whether currseId exists in that user wishlist array if yes we can give an exception.

**Comment by dhwaj1902** [comment]
Please assign this issue to me if this is a valid issue.

**Comment by Abhishek-kumar09** [comment]
Sure @dhwaj1902 Go ahead.
This issue still persist right.
